/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function connect(path: string, create: boolean) {
    return invoke()<null>("connect", { path,create })
}

export function disconnect() {
    return invoke()<null>("disconnect")
}

export function isConnected() {
    return invoke()<boolean>("is_connected")
}

export function getTimelines() {
    return invoke()<Timeline[]>("get_timelines")
}

export function getEvents() {
    return invoke()<Event[]>("get_events")
}

export type Timeline = { uuid: string; title: string; color: string; parent_uuid: string | null }
export type Event = { uuid: string; timestamp: number; color: string; content: string; timelines: string[] }
